name: travel_booking_app
description: A complete Travel Booking mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.15.0
  webview_flutter_wkwebview: ^3.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

